### ISSUE TITLE
Allow deleting old tweets by downloading your twitter data

### ISSUE THREAD

**Issue by micahflee** [micahflee/semiphemeral#55]
Similar to the `--unlike` setting, it would be cool to allow people to delete their old tweets in situations where the Twitter API only returns the most recent 3000 tweets, and refuses to return anything older.

Related to #54, #41, #12

**Comment by peteyreplies** [comment]
This would be great!

**Comment by galonsky** [comment]
I'm not really familiar with the semiphemeral codebase, but I just ended up writing a script for this myself since it seemed pretty simple: https://github.com/galonsky/delete_twitter_via_archive/blob/main/delete_via_archive.py

I'd be happy to add to semiphemeral if someone could point me to the write place.

**Comment by kees** [comment]
With #23 now merged, I *think* this bug can be closed. If not, please reopen. :)
